#!/usr/bin/env groovy
node {	 
	/* Requires the Docker Pipeline plugin to be installed */ 
	docker.image('maven:3-alpine').inside('-v $HOME/.m2:/root/.m2') {
		stage('Build') {
			sh 'mvn -f jenkins1/pom.xml -B -DskipTests clean package'
		}
		stage('Test') {
			try {
				sh 'mvn -f jenkins1/pom.xml test'
			}
			finally {
				junit 'jenkins1/target/**/*.xml'
			}
		}
	}
}
